### ISSUE TITLE
Readthis as a store for Rack::Cache?

### ISSUE THREAD

**Issue by trostli** [sorentwo/readthis#43]
Hello,

I was wondering if it's possible to use readthis as a store for Rack::Cache ? I'm aware of the [redis-rack-cache](https://github.com/redis-store/redis-rack-cache) gem, but wasn't sure if this would play nice with readthis. Thanks in advance for any guidance!

**Comment by sorentwo** [comment]
I'm fairly positive that `readthis` won't work with `redis-rack-cache`, purely because that has a hard dependency on `redis-store`. However, I think it would be extremely simple to port it. All of my projects use Fastly or another full blown CDN, so I don't have a use case to test with. If you're interesting in starting the project I'd be happy to advise or help out though.

**Comment by sorentwo** [comment]
My comment from two weeks ago still stands, I'm happy to advise. However, this won't be part of Readthis so I'm going to close this issue.

**Comment by beejamin** [comment]
Hi,

I've been working on migrating an app I work on to use readthis, and I would really like to be able to use it as a store for Rack::Cache, too. I'm game for porting redis-rack-cache (readthis-rack-cache?), but if you wouldn't mind pointing me in the right direction, I'd be very grateful. 

Do you think it's worth implementing something like redis-store's API (which provides a factory for setting up the client, amongst other things)? Or simpler/better to just instance the client within the readthis-rack-cache code directly?

Any thoughts or comments would be great - thanks!
